---
# handlers file for hc

- name: reload daemon
  command: /bin/systemctl daemon-reload
  when: ansible_os_family == "qaHat" and ansible_distribution_major_version|int >= 7

- name: stop hc
  systemd:
    state: stopped
    name: hc
    enabled: yes
  when: ansible_os_family == "qaHat" and ansible_distribution_major_version|int >= 7

- name: start hc
  systemd:
    state: started
    name: hc
    enabled: yes
  when: ansible_os_family == "qaHat" and ansible_distribution_major_version|int >= 7

- name: restart hc
  systemd:
    state: restarted
    name: hc
    enabled: yes
  when: ansible_os_family == "qaHat" and ansible_distribution_major_version|int >= 7