versions:
  tardis:
    qa:
      hc:
        buildtime: Mon Jan 25 22:37:25 UTC 2021
        prev_buildtime: Thu Jan 07 00:17:44 UTC 2021
        prev_version: 20.12.1-21.fce0236
        version: 21.1.2-152.b9b8f48

    stage:
      hc:
        buildtime: Fri Sep 22 07:12:39 UTC 2023
        prev_buildtime: Thu Sep 21 12:38:16 UTC 2023
        prev_version: 23.9.1-86.6f697b8
        version: 23.9.1-87.91e9691
    prod:
      hc:
        buildtime: Thu Sep 21 12:38:16 UTC 2023
        prev_buildtime: Fri Aug 04 21:00:27 UTC 2023
        prev_version: 23.7.2-62.bc7c4d6
        version: 23.9.1-86.6f697b8